# Generated by Django 5.0.14 on 2026-06-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company', max_length=200)),
                ('company_address', models.TextField(default='')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('pf_enabled', models.BooleanField(default=True)),
                ('esi_enabled', models.BooleanField(default=True)),
                ('pt_enabled', models.BooleanField(default=True)),
                ('work_start_time', models.TimeField(default='09:00:00')),
                ('grace_minutes', models.IntegerField(default=15)),
                ('casual_leave_quota', models.IntegerField(default=12)),
                ('sick_leave_quota', models.IntegerField(default=12)),
                ('earned_leave_quota', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
