# Generated by Django 5.0.14 on 2026-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='minimum_working_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_end_time',
            field=models.TimeField(default='18:00:00'),
        ),
    ]
