# Generated by Django 5.0.14 on 2026-06-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRSession',
        ),
    ]
