# Generated by Django 5.0.14 on 2026-06-12 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='employee_qrs/')),
                ('signature', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_qrs',
            },
        ),
    ]
